// Generated by gencpp from file simple_service_communication/ServiceResponse.msg
// DO NOT EDIT!


#ifndef SIMPLE_SERVICE_COMMUNICATION_MESSAGE_SERVICERESPONSE_H
#define SIMPLE_SERVICE_COMMUNICATION_MESSAGE_SERVICERESPONSE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace simple_service_communication
{
template <class ContainerAllocator>
struct ServiceResponse_
{
  typedef ServiceResponse_<ContainerAllocator> Type;

  ServiceResponse_()
    : sum(0)
    , product(0)
    , equal(false)  {
    }
  ServiceResponse_(const ContainerAllocator& _alloc)
    : sum(0)
    , product(0)
    , equal(false)  {
  (void)_alloc;
    }



   typedef int32_t _sum_type;
  _sum_type sum;

   typedef int32_t _product_type;
  _product_type product;

   typedef uint8_t _equal_type;
  _equal_type equal;





  typedef boost::shared_ptr< ::simple_service_communication::ServiceResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::simple_service_communication::ServiceResponse_<ContainerAllocator> const> ConstPtr;

}; // struct ServiceResponse_

typedef ::simple_service_communication::ServiceResponse_<std::allocator<void> > ServiceResponse;

typedef boost::shared_ptr< ::simple_service_communication::ServiceResponse > ServiceResponsePtr;
typedef boost::shared_ptr< ::simple_service_communication::ServiceResponse const> ServiceResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::simple_service_communication::ServiceResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::simple_service_communication::ServiceResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::simple_service_communication::ServiceResponse_<ContainerAllocator1> & lhs, const ::simple_service_communication::ServiceResponse_<ContainerAllocator2> & rhs)
{
  return lhs.sum == rhs.sum &&
    lhs.product == rhs.product &&
    lhs.equal == rhs.equal;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::simple_service_communication::ServiceResponse_<ContainerAllocator1> & lhs, const ::simple_service_communication::ServiceResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace simple_service_communication

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::simple_service_communication::ServiceResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::simple_service_communication::ServiceResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::simple_service_communication::ServiceResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::simple_service_communication::ServiceResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::simple_service_communication::ServiceResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::simple_service_communication::ServiceResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::simple_service_communication::ServiceResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "5f8888d4aade437f7ede68b2b4a1e75e";
  }

  static const char* value(const ::simple_service_communication::ServiceResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x5f8888d4aade437fULL;
  static const uint64_t static_value2 = 0x7ede68b2b4a1e75eULL;
};

template<class ContainerAllocator>
struct DataType< ::simple_service_communication::ServiceResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "simple_service_communication/ServiceResponse";
  }

  static const char* value(const ::simple_service_communication::ServiceResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::simple_service_communication::ServiceResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int32 sum\n"
"int32 product\n"
"bool equal\n"
;
  }

  static const char* value(const ::simple_service_communication::ServiceResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::simple_service_communication::ServiceResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.sum);
      stream.next(m.product);
      stream.next(m.equal);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ServiceResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::simple_service_communication::ServiceResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::simple_service_communication::ServiceResponse_<ContainerAllocator>& v)
  {
    s << indent << "sum: ";
    Printer<int32_t>::stream(s, indent + "  ", v.sum);
    s << indent << "product: ";
    Printer<int32_t>::stream(s, indent + "  ", v.product);
    s << indent << "equal: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.equal);
  }
};

} // namespace message_operations
} // namespace ros

#endif // SIMPLE_SERVICE_COMMUNICATION_MESSAGE_SERVICERESPONSE_H
