// Generated by gencpp from file simple_service_communication/ServiceRequest.msg
// DO NOT EDIT!


#ifndef SIMPLE_SERVICE_COMMUNICATION_MESSAGE_SERVICEREQUEST_H
#define SIMPLE_SERVICE_COMMUNICATION_MESSAGE_SERVICEREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace simple_service_communication
{
template <class ContainerAllocator>
struct ServiceRequest_
{
  typedef ServiceRequest_<ContainerAllocator> Type;

  ServiceRequest_()
    : a(0)
    , b(0)  {
    }
  ServiceRequest_(const ContainerAllocator& _alloc)
    : a(0)
    , b(0)  {
  (void)_alloc;
    }



   typedef int32_t _a_type;
  _a_type a;

   typedef int32_t _b_type;
  _b_type b;





  typedef boost::shared_ptr< ::simple_service_communication::ServiceRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::simple_service_communication::ServiceRequest_<ContainerAllocator> const> ConstPtr;

}; // struct ServiceRequest_

typedef ::simple_service_communication::ServiceRequest_<std::allocator<void> > ServiceRequest;

typedef boost::shared_ptr< ::simple_service_communication::ServiceRequest > ServiceRequestPtr;
typedef boost::shared_ptr< ::simple_service_communication::ServiceRequest const> ServiceRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::simple_service_communication::ServiceRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::simple_service_communication::ServiceRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::simple_service_communication::ServiceRequest_<ContainerAllocator1> & lhs, const ::simple_service_communication::ServiceRequest_<ContainerAllocator2> & rhs)
{
  return lhs.a == rhs.a &&
    lhs.b == rhs.b;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::simple_service_communication::ServiceRequest_<ContainerAllocator1> & lhs, const ::simple_service_communication::ServiceRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace simple_service_communication

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::simple_service_communication::ServiceRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::simple_service_communication::ServiceRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::simple_service_communication::ServiceRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::simple_service_communication::ServiceRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::simple_service_communication::ServiceRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::simple_service_communication::ServiceRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::simple_service_communication::ServiceRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ef8322123148e475e3e93a1f609b2f70";
  }

  static const char* value(const ::simple_service_communication::ServiceRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xef8322123148e475ULL;
  static const uint64_t static_value2 = 0xe3e93a1f609b2f70ULL;
};

template<class ContainerAllocator>
struct DataType< ::simple_service_communication::ServiceRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "simple_service_communication/ServiceRequest";
  }

  static const char* value(const ::simple_service_communication::ServiceRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::simple_service_communication::ServiceRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int32 a\n"
"int32 b\n"
"\n"
;
  }

  static const char* value(const ::simple_service_communication::ServiceRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::simple_service_communication::ServiceRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.a);
      stream.next(m.b);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ServiceRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::simple_service_communication::ServiceRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::simple_service_communication::ServiceRequest_<ContainerAllocator>& v)
  {
    s << indent << "a: ";
    Printer<int32_t>::stream(s, indent + "  ", v.a);
    s << indent << "b: ";
    Printer<int32_t>::stream(s, indent + "  ", v.b);
  }
};

} // namespace message_operations
} // namespace ros

#endif // SIMPLE_SERVICE_COMMUNICATION_MESSAGE_SERVICEREQUEST_H
