// Generated by gencpp from file simple_service_communication/Service.msg
// DO NOT EDIT!


#ifndef SIMPLE_SERVICE_COMMUNICATION_MESSAGE_SERVICE_H
#define SIMPLE_SERVICE_COMMUNICATION_MESSAGE_SERVICE_H

#include <ros/service_traits.h>


#include <simple_service_communication/ServiceRequest.h>
#include <simple_service_communication/ServiceResponse.h>


namespace simple_service_communication
{

struct Service
{

typedef ServiceRequest Request;
typedef ServiceResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct Service
} // namespace simple_service_communication


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::simple_service_communication::Service > {
  static const char* value()
  {
    return "265403904a641754bdb371c888af48bf";
  }

  static const char* value(const ::simple_service_communication::Service&) { return value(); }
};

template<>
struct DataType< ::simple_service_communication::Service > {
  static const char* value()
  {
    return "simple_service_communication/Service";
  }

  static const char* value(const ::simple_service_communication::Service&) { return value(); }
};


// service_traits::MD5Sum< ::simple_service_communication::ServiceRequest> should match
// service_traits::MD5Sum< ::simple_service_communication::Service >
template<>
struct MD5Sum< ::simple_service_communication::ServiceRequest>
{
  static const char* value()
  {
    return MD5Sum< ::simple_service_communication::Service >::value();
  }
  static const char* value(const ::simple_service_communication::ServiceRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::simple_service_communication::ServiceRequest> should match
// service_traits::DataType< ::simple_service_communication::Service >
template<>
struct DataType< ::simple_service_communication::ServiceRequest>
{
  static const char* value()
  {
    return DataType< ::simple_service_communication::Service >::value();
  }
  static const char* value(const ::simple_service_communication::ServiceRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::simple_service_communication::ServiceResponse> should match
// service_traits::MD5Sum< ::simple_service_communication::Service >
template<>
struct MD5Sum< ::simple_service_communication::ServiceResponse>
{
  static const char* value()
  {
    return MD5Sum< ::simple_service_communication::Service >::value();
  }
  static const char* value(const ::simple_service_communication::ServiceResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::simple_service_communication::ServiceResponse> should match
// service_traits::DataType< ::simple_service_communication::Service >
template<>
struct DataType< ::simple_service_communication::ServiceResponse>
{
  static const char* value()
  {
    return DataType< ::simple_service_communication::Service >::value();
  }
  static const char* value(const ::simple_service_communication::ServiceResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // SIMPLE_SERVICE_COMMUNICATION_MESSAGE_SERVICE_H
