// Generated by gencpp from file service_pkg/TwoNumbers.msg
// DO NOT EDIT!


#ifndef SERVICE_PKG_MESSAGE_TWONUMBERS_H
#define SERVICE_PKG_MESSAGE_TWONUMBERS_H

#include <ros/service_traits.h>


#include <service_pkg/TwoNumbersRequest.h>
#include <service_pkg/TwoNumbersResponse.h>


namespace service_pkg
{

struct TwoNumbers
{

typedef TwoNumbersRequest Request;
typedef TwoNumbersResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct TwoNumbers
} // namespace service_pkg


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::service_pkg::TwoNumbers > {
  static const char* value()
  {
    return "c9430c0754d7eee705aa42d6ef2f22e7";
  }

  static const char* value(const ::service_pkg::TwoNumbers&) { return value(); }
};

template<>
struct DataType< ::service_pkg::TwoNumbers > {
  static const char* value()
  {
    return "service_pkg/TwoNumbers";
  }

  static const char* value(const ::service_pkg::TwoNumbers&) { return value(); }
};


// service_traits::MD5Sum< ::service_pkg::TwoNumbersRequest> should match
// service_traits::MD5Sum< ::service_pkg::TwoNumbers >
template<>
struct MD5Sum< ::service_pkg::TwoNumbersRequest>
{
  static const char* value()
  {
    return MD5Sum< ::service_pkg::TwoNumbers >::value();
  }
  static const char* value(const ::service_pkg::TwoNumbersRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::service_pkg::TwoNumbersRequest> should match
// service_traits::DataType< ::service_pkg::TwoNumbers >
template<>
struct DataType< ::service_pkg::TwoNumbersRequest>
{
  static const char* value()
  {
    return DataType< ::service_pkg::TwoNumbers >::value();
  }
  static const char* value(const ::service_pkg::TwoNumbersRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::service_pkg::TwoNumbersResponse> should match
// service_traits::MD5Sum< ::service_pkg::TwoNumbers >
template<>
struct MD5Sum< ::service_pkg::TwoNumbersResponse>
{
  static const char* value()
  {
    return MD5Sum< ::service_pkg::TwoNumbers >::value();
  }
  static const char* value(const ::service_pkg::TwoNumbersResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::service_pkg::TwoNumbersResponse> should match
// service_traits::DataType< ::service_pkg::TwoNumbers >
template<>
struct DataType< ::service_pkg::TwoNumbersResponse>
{
  static const char* value()
  {
    return DataType< ::service_pkg::TwoNumbers >::value();
  }
  static const char* value(const ::service_pkg::TwoNumbersResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // SERVICE_PKG_MESSAGE_TWONUMBERS_H
