// Generated by gencpp from file service_pkg/TwoNumbersRequest.msg
// DO NOT EDIT!


#ifndef SERVICE_PKG_MESSAGE_TWONUMBERSREQUEST_H
#define SERVICE_PKG_MESSAGE_TWONUMBERSREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace service_pkg
{
template <class ContainerAllocator>
struct TwoNumbersRequest_
{
  typedef TwoNumbersRequest_<ContainerAllocator> Type;

  TwoNumbersRequest_()
    : a(0)
    , b(0)  {
    }
  TwoNumbersRequest_(const ContainerAllocator& _alloc)
    : a(0)
    , b(0)  {
  (void)_alloc;
    }



   typedef int32_t _a_type;
  _a_type a;

   typedef int32_t _b_type;
  _b_type b;





  typedef boost::shared_ptr< ::service_pkg::TwoNumbersRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::service_pkg::TwoNumbersRequest_<ContainerAllocator> const> ConstPtr;

}; // struct TwoNumbersRequest_

typedef ::service_pkg::TwoNumbersRequest_<std::allocator<void> > TwoNumbersRequest;

typedef boost::shared_ptr< ::service_pkg::TwoNumbersRequest > TwoNumbersRequestPtr;
typedef boost::shared_ptr< ::service_pkg::TwoNumbersRequest const> TwoNumbersRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::service_pkg::TwoNumbersRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::service_pkg::TwoNumbersRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::service_pkg::TwoNumbersRequest_<ContainerAllocator1> & lhs, const ::service_pkg::TwoNumbersRequest_<ContainerAllocator2> & rhs)
{
  return lhs.a == rhs.a &&
    lhs.b == rhs.b;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::service_pkg::TwoNumbersRequest_<ContainerAllocator1> & lhs, const ::service_pkg::TwoNumbersRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace service_pkg

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::service_pkg::TwoNumbersRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::service_pkg::TwoNumbersRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::service_pkg::TwoNumbersRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::service_pkg::TwoNumbersRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::service_pkg::TwoNumbersRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::service_pkg::TwoNumbersRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::service_pkg::TwoNumbersRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ef8322123148e475e3e93a1f609b2f70";
  }

  static const char* value(const ::service_pkg::TwoNumbersRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xef8322123148e475ULL;
  static const uint64_t static_value2 = 0xe3e93a1f609b2f70ULL;
};

template<class ContainerAllocator>
struct DataType< ::service_pkg::TwoNumbersRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "service_pkg/TwoNumbersRequest";
  }

  static const char* value(const ::service_pkg::TwoNumbersRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::service_pkg::TwoNumbersRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int32 a\n"
"int32 b\n"
;
  }

  static const char* value(const ::service_pkg::TwoNumbersRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::service_pkg::TwoNumbersRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.a);
      stream.next(m.b);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct TwoNumbersRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::service_pkg::TwoNumbersRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::service_pkg::TwoNumbersRequest_<ContainerAllocator>& v)
  {
    s << indent << "a: ";
    Printer<int32_t>::stream(s, indent + "  ", v.a);
    s << indent << "b: ";
    Printer<int32_t>::stream(s, indent + "  ", v.b);
  }
};

} // namespace message_operations
} // namespace ros

#endif // SERVICE_PKG_MESSAGE_TWONUMBERSREQUEST_H
