// Generated by gencpp from file work1/AddTwoInts.msg
// DO NOT EDIT!


#ifndef WORK1_MESSAGE_ADDTWOINTS_H
#define WORK1_MESSAGE_ADDTWOINTS_H

#include <ros/service_traits.h>


#include <work1/AddTwoIntsRequest.h>
#include <work1/AddTwoIntsResponse.h>


namespace work1
{

struct AddTwoInts
{

typedef AddTwoIntsRequest Request;
typedef AddTwoIntsResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct AddTwoInts
} // namespace work1


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::work1::AddTwoInts > {
  static const char* value()
  {
    return "1859b27a2ca347eed9068f108f06d918";
  }

  static const char* value(const ::work1::AddTwoInts&) { return value(); }
};

template<>
struct DataType< ::work1::AddTwoInts > {
  static const char* value()
  {
    return "work1/AddTwoInts";
  }

  static const char* value(const ::work1::AddTwoInts&) { return value(); }
};


// service_traits::MD5Sum< ::work1::AddTwoIntsRequest> should match
// service_traits::MD5Sum< ::work1::AddTwoInts >
template<>
struct MD5Sum< ::work1::AddTwoIntsRequest>
{
  static const char* value()
  {
    return MD5Sum< ::work1::AddTwoInts >::value();
  }
  static const char* value(const ::work1::AddTwoIntsRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::work1::AddTwoIntsRequest> should match
// service_traits::DataType< ::work1::AddTwoInts >
template<>
struct DataType< ::work1::AddTwoIntsRequest>
{
  static const char* value()
  {
    return DataType< ::work1::AddTwoInts >::value();
  }
  static const char* value(const ::work1::AddTwoIntsRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::work1::AddTwoIntsResponse> should match
// service_traits::MD5Sum< ::work1::AddTwoInts >
template<>
struct MD5Sum< ::work1::AddTwoIntsResponse>
{
  static const char* value()
  {
    return MD5Sum< ::work1::AddTwoInts >::value();
  }
  static const char* value(const ::work1::AddTwoIntsResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::work1::AddTwoIntsResponse> should match
// service_traits::DataType< ::work1::AddTwoInts >
template<>
struct DataType< ::work1::AddTwoIntsResponse>
{
  static const char* value()
  {
    return DataType< ::work1::AddTwoInts >::value();
  }
  static const char* value(const ::work1::AddTwoIntsResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // WORK1_MESSAGE_ADDTWOINTS_H
