// Generated by gencpp from file packge_ser_cli/TwoNumbers.msg
// DO NOT EDIT!


#ifndef PACKGE_SER_CLI_MESSAGE_TWONUMBERS_H
#define PACKGE_SER_CLI_MESSAGE_TWONUMBERS_H

#include <ros/service_traits.h>


#include <packge_ser_cli/TwoNumbersRequest.h>
#include <packge_ser_cli/TwoNumbersResponse.h>


namespace packge_ser_cli
{

struct TwoNumbers
{

typedef TwoNumbersRequest Request;
typedef TwoNumbersResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct TwoNumbers
} // namespace packge_ser_cli


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::packge_ser_cli::TwoNumbers > {
  static const char* value()
  {
    return "c9430c0754d7eee705aa42d6ef2f22e7";
  }

  static const char* value(const ::packge_ser_cli::TwoNumbers&) { return value(); }
};

template<>
struct DataType< ::packge_ser_cli::TwoNumbers > {
  static const char* value()
  {
    return "packge_ser_cli/TwoNumbers";
  }

  static const char* value(const ::packge_ser_cli::TwoNumbers&) { return value(); }
};


// service_traits::MD5Sum< ::packge_ser_cli::TwoNumbersRequest> should match
// service_traits::MD5Sum< ::packge_ser_cli::TwoNumbers >
template<>
struct MD5Sum< ::packge_ser_cli::TwoNumbersRequest>
{
  static const char* value()
  {
    return MD5Sum< ::packge_ser_cli::TwoNumbers >::value();
  }
  static const char* value(const ::packge_ser_cli::TwoNumbersRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::packge_ser_cli::TwoNumbersRequest> should match
// service_traits::DataType< ::packge_ser_cli::TwoNumbers >
template<>
struct DataType< ::packge_ser_cli::TwoNumbersRequest>
{
  static const char* value()
  {
    return DataType< ::packge_ser_cli::TwoNumbers >::value();
  }
  static const char* value(const ::packge_ser_cli::TwoNumbersRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::packge_ser_cli::TwoNumbersResponse> should match
// service_traits::MD5Sum< ::packge_ser_cli::TwoNumbers >
template<>
struct MD5Sum< ::packge_ser_cli::TwoNumbersResponse>
{
  static const char* value()
  {
    return MD5Sum< ::packge_ser_cli::TwoNumbers >::value();
  }
  static const char* value(const ::packge_ser_cli::TwoNumbersResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::packge_ser_cli::TwoNumbersResponse> should match
// service_traits::DataType< ::packge_ser_cli::TwoNumbers >
template<>
struct DataType< ::packge_ser_cli::TwoNumbersResponse>
{
  static const char* value()
  {
    return DataType< ::packge_ser_cli::TwoNumbers >::value();
  }
  static const char* value(const ::packge_ser_cli::TwoNumbersResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // PACKGE_SER_CLI_MESSAGE_TWONUMBERS_H
